### ISSUE TITLE
Multi db tests behave differently on different dbs

### ISSUE THREAD

**Issue by obiwanus** [pytest-dev/pytest-django#423] opened 2016-11-18 00:41 UTC
I have two identical sqlite databases for testing
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'first',
    },
    'second': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'second',
    },
}
```
At the start of each test the default database is clean, but the second database contains the data from the previous test runs.
The transaction setting `pytestmark = pytest.mark.django_db(transaction=True)` doesn't seem to have any effect on the default database behaviour - it is always clean for every test regardless of whether `transaction` is `True` or `False`. The same is true for the second database except it's always dirty.

**Comment by blueyed** [comment] 2016-11-18 11:29
Are you using `--reuse-db` and/or `--no-migrations`?
What Django and pytest-django versions are you using?

IIRC Django only runs management commands (including migrations etc) on the default DB only.
Not sure about tests though - although we should be using Django's behavior/methods there already.

**Comment by obiwanus** [comment] 2016-11-19 00:35
I'm not using `--reuse-db` or `--no-migrations`, just running `pytest tests`.

`pytest-django==3.0.0`, `Django==1.10.3`

My second database has no migrations, so I assume Django only does `syncdb` for it. I don't see though how this would affect tests - migrations should only be applied once before running the whole suite anyway, not between test runs, right?

**Comment by obiwanus** [comment] 2016-11-19 00:38
I'll try to create a minimal working example to reproduce the issue on Monday

**Comment by obiwanus** [comment] 2016-11-21 00:47
OK I've created a repo with a minimal example that should demonstrate the issue

https://github.com/obiwanus/pytest-django-bug

Please let me know if you have any problems with it. Thanks

**Comment by blueyed** [comment] 2016-11-24 14:06
I think a failing test (as a PR) would be better.  But the above might be enough for others to look at already.

**Comment by vbarbaresi** [comment] 2017-10-26 13:43
Django only deals with the default database per default, as an optimization. [Link to the doc](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.TransactionTestCase.multi_db)
You have to wrap the test into a class and define `multi_db = True` for it to handle the 2 databases.

I found this in pytest-django doc: https://github.com/pytest-dev/pytest-django/blob/master/docs/database.rst#tests-requiring-multiple-databases

To implement the option in pytest-django without having to create classes, I hacked here:

```diff
diff --git a/pytest_django/fixtures.py b/pytest_django/fixtures.py
index 692e061..e95122e 100644
--- a/pytest_django/fixtures.py
+++ b/pytest_django/fixtures.py
@@ -119,6 +119,7 @@ def _django_db_fixture_helper(transactional, request, django_db_blocker):
     else:
         from django.test import TestCase as django_case

+    django_case.multi_db = True
     test_case = django_case(methodName='__init__')
     test_case._pre_setup()
     request.addfinalizer(test_case._post_teardown)
```

We could enable this on demand with a `pytest.mark.multi_db` marker, what do you think?

**Comment by blueyed** [comment] 2017-10-26 14:16
@vbarbaresi 
See https://github.com/pytest-dev/pytest-django/pull/431.

**Comment by bluetech** [comment] 2021-05-07 09:47
I'll close this issue as a duplicate of general multi-db support.

**Closed by bluetech** 2021-05-07 09:47 UTC
