### ISSUE TITLE
Problem with Pytest 2.8 and Django settings

### ISSUE THREAD

**Issue by kottenator** [pytest-dev/pytest-django#272] opened 2015-09-24 18:08 UTC
After update to Pytest 2.8 my tests started failing.

The problem is that when I configure Django setings in `conftest.py`:

```py
from django.conf import settings

def pytest_configure():
    settings.configure(DATABASES=...)
```

Pytest 2.8 tries to read some properties from `settings` before they're configured and it raises an error. So I have to do some workaround to make it work:

```py
from django import conf

def pytest_configure():
    conf.settings.configure(DATABASES=...)
```
It's a problem of `pytest`, not `pytest-django`. But I think you could mention this workaround in your documentation.

**Comment by blueyed** [comment] 2015-09-24 18:58
> Pytest 2.8 tries to read some properties from settings before they're configured and it raises an error. 

Have you reported this for pytest?
Can you provide more information (e.g. a traceback), please?

**Comment by blueyed** [comment] 2015-09-24 19:00
..having a (now failing) test for this in pytest-django's test suite would be sweet.
Could you come up  with one, using the `runpytest` method, see tests/test_django_settings_module.py.

**Comment by kottenator** [comment] 2015-09-24 19:23
@blueyed: here is the stacktrace: http://pastebin.com/dv4rp7c1
I haven't reported this to Pytest yet, will do this now

**Comment by blueyed** [comment] 2015-09-24 20:21
@kottenator 
I think the problem is "just" that settings are accessed too early, and that probably your workaround (`conf.settings`) is not working as expected?  Compare it to https://docs.djangoproject.com/en/1.8/topics/settings/#django.conf.settings.configure.

**Comment by kottenator** [comment] 2015-09-24 20:25
My workaround with `conf.settings` does work. I just wanted to tell you about the problem. And I thought that you could add this workaround to `pytest-django` docs (in the section about `django.conf.settings.configure()`) and to explain why not to do `from django.conf import settings`

**Comment by blueyed** [comment] 2015-09-24 21:15
I understand that.
AFAIK `django.conf.settings` is only meant to be imported as `settings`, but I might be wrong.

I would rather like to fix this in pytest-django, than document how to work around that - especially if that's not the way how settings are meant to be used.

**Comment by blueyed** [comment] 2015-09-24 23:14
Copied from the pytest issue (from me):

It's not pytest doing something special with `settings`, but accessing it in general will trigger the Django settings machinery / setup.
pytest-django's job is it to call e.g. `django.setup()` before that and/or prepare everything.

I think the proper workaround for now would be to call `django.setup()` in `pytest_configure`, instead of importing/using settings via conf.settings. There are likely some related issues/tickets in pytest-django.  It's a tricky and changing area.

**Comment by blueyed** [comment] 2015-09-24 23:21
See https://github.com/pytest-dev/pytest-django/issues?q=is%3Aissue+conftest+setup, e.g. #146.

Given your initial information, it might be a regression with pytest 2.8 indeed, but then probably pytest-django needs to adopt to it.

For now, I've added pytest 2.8.0 to https://github.com/pytest-dev/pytest-django/pull/262 - a PR to update the used versions.

**Comment by pelme** [comment] 2015-09-26 12:52
Hmm, this actually fails in the pytest-django test suite too.

The recent pluggy changes in pytest looks suspicious, I will try to dig into this more.

**Comment by pelme** [comment] 2015-09-26 13:17
I narrowed this down a bit and reported it for pytest:
https://github.com/pytest-dev/pytest/issues/1073

**Comment by kottenator** [comment] 2015-09-27 15:30
@blueyed: sorry, I had no chance to look into GitHub till now. I understand what causes this particular problem with `django.conf.settings`, that django is not set up at the moment. That's why I have this workaround. But this is at the same time Django's and pytest's problem. According to @pelme 's #1073 this problem may occur in other cases/frameworks. And I think it's more pytest's problem rather than Django's :)

**Comment by blueyed** [comment] 2015-09-27 16:40
@kottenator 
Yes you are right, see also my previous comment at https://github.com/pytest-dev/pytest/issues/1059#issuecomment-143551288..  Sorry for the confusion.

**Comment by pelme** [comment] 2015-09-28 09:26
There is some work going on in pluggy to fix this. I'd like to have this resolved+released in pytest 2.8.1 before releasing the next version of pytest-django since this breaks a documented way to configure the settings.

**Comment by blueyed** [comment] 2015-09-29 20:15
pytest 2.8.1 has been released: https://github.com/pytest-dev/pytest-django/pull/276

**Comment by pelme** [comment] 2015-10-02 16:38
I have updated the pytest-django test suite to run with pytest 2.8.1 and this should no longer be a problem. :)

**Closed by pelme** 2015-10-02 16:38 UTC
Labels: bug, release-blocker, upstream
