### ISSUE TITLE
Latest PyPI package does not include django_assert_num_queries

### ISSUE THREAD

**Issue by IsaacMother** [pytest-dev/pytest-django#474] opened 2017-04-07 09:42 UTC
Installation through `pip install pytest-django` does not include `django_assert_num_queries` fixture.

`pytest_django/fixtures.py`:
~~~{.py}
__all__ = ['django_db_setup', 'db', 'transactional_db', 'admin_user',
           'django_user_model', 'django_username_field',
           'client', 'admin_client', 'rf', 'settings', 'live_server',
           '_live_server_helper']
~~~

**Comment by blueyed** [comment] 2017-04-07 10:10
Duplicate of https://github.com/pytest-dev/pytest-django/issues/473?!

**Closed by blueyed** 2017-04-07 10:10 UTC
