### ISSUE TITLE
python3 setup.py test fails with either py3.6 or py3.7

### ISSUE THREAD

**Issue by kekePower** [pytest-dev/pytest-django#688] opened 2019-01-10 20:24 UTC
Hi.

I tried with both py3.6 and py3.7 and it fails on both.

Here is a log from a build on Mageia 7 with py3.7.
https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20190110200934.kekepower.duvel.2933/log/python-pytest-django-3.4.5-1.mga7/build.0.20190110201035.log

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    entry_points={'pytest11': ['django = pytest_django.plugin']})
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/iurt/rpmbuild/BUILD/pytest-django-3.4.5/pytest_django_test/db_helpers.py", line 12, in <module>
    _settings = settings.DATABASES['default']
  File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by blueyed** [comment] 2019-01-10 23:02
Can you use tox?  (this appears to be for a distro?!)
Otherwise you need to set some env for the settings: https://github.com/pytest-dev/pytest-django/blob/bbb8339db96ad680eab1f517b5c582cfe819775b/tox.ini#L29-L33

Maybe this could default to sqlite?!

**Comment by kekePower** [comment] 2019-01-10 23:30
I tried this outside of building a package.

```
% export DJANGO_SETTINGS_MODULE=pytest_django_test.settings_sqlite
% PYTHONPATH=$(pwd) LC_ALL=C.UTF-8 py.test-3.6 -r s -k 'not test_stdouterrin_setnull' tests
```

Results:
```
======================================= test session starts ========================================
platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
Django settings: pytest_django_test.settings_sqlite (from environment variable)
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/BUILD/pytest-django-3.4.5/.hypothesis/examples')
rootdir: /BUILD/pytest-django-3.4.5, inifile: setup.cfg
plugins: django-3.4.5, forked-0.2, cov-2.6.0, hypothesis-3.85.1
collected 162 items / 1 skipped

tests/test_database.py ...........s........................                                  [ 22%]
tests/test_db_setup.py .s.sFs..                                                              [ 27%]
tests/test_django_settings_module.py .........F.....                                         [ 36%]
tests/test_doctest.txt .                                                                     [ 37%]
tests/test_environment.py ...................                                                [ 48%]
tests/test_fixtures.py ...............................................                       [ 77%]
tests/test_initialization.py .                                                               [ 78%]
tests/test_manage_py_scan.py ......                                                          [ 82%]
tests/test_unittest.py ..................                                                    [ 93%]
tests/test_urls.py ....                                                                      [ 95%]
tests/test_without_django_loaded.py .......                                                  [100%]

============================================= FAILURES =============================================
__________________________ TestSqliteWithXdist.test_sqlite_in_memory_used __________________________

self = <test_db_setup.TestSqliteWithXdist object at 0x7f85371c6f28>
django_testdir = <Testdir local('/tmp/pytest-of-stig/pytest-26/test_sqlite_in_memory_used0')>

    def test_sqlite_in_memory_used(self, django_testdir):

        django_testdir.create_test_module(
            """
            import pytest
            from django.db import connections

            @pytest.mark.django_db
            def test_a():
                (conn, ) = connections.all()

                assert conn.vendor == 'sqlite'
                db_name = conn.creation._get_test_db_name()
                assert 'file:memorydb' in db_name or db_name == ':memory:'
        """
        )

        result = django_testdir.runpytest_subprocess("--tb=short", "-vv", "-n1")
>       assert result.ret == 0
E       assert 4 == 0
E        +  where 4 = <_pytest.pytester.RunResult object at 0x7f85371701d0>.ret

/BUILD/pytest-django-3.4.5/tests/test_db_setup.py:212: AssertionError
--------------------------------------- Captured stdout call ---------------------------------------
running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-stig/pytest-26/test_sqlite_in_memory_used0/runpytest-0 --tb=short -vv -n1
     in: /tmp/pytest-of-stig/pytest-26/test_sqlite_in_memory_used0
--------------------------------------- Captured stderr call ---------------------------------------
usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: -n1
  inifile: /tmp/pytest-of-stig/pytest-26/test_sqlite_in_memory_used0/tox.ini
  rootdir: /tmp/pytest-of-stig/pytest-26/test_sqlite_in_memory_used0
_____________________________ test_django_not_loaded_without_settings ______________________________

testdir = <Testdir local('/tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0')>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f853711bac8>

    def test_django_not_loaded_without_settings(testdir, monkeypatch):
        """
        Make sure Django is not imported at all if no Django settings is specified.
        """
        monkeypatch.delenv("DJANGO_SETTINGS_MODULE")
        testdir.makepyfile(
            """
            import sys
            def test_settings():
                assert 'django' not in sys.modules
        """
        )
        result = testdir.runpytest_subprocess()
>       result.stdout.fnmatch_lines(["*1 passed*"])
E       Failed: nomatch: '*1 passed*'
E           and: '============================= test session starts =============================='
E           and: 'platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0'
E           and: "hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0/.hypothesis/examples')"
E           and: 'rootdir: /tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0, inifile:'
E           and: 'plugins: django-3.4.5, forked-0.2, cov-2.6.0, hypothesis-3.85.1'
E           and: 'collected 1 item'
E           and: ''
E           and: 'test_django_not_loaded_without_settings.py F                             [100%]'
E           and: ''
E           and: '=================================== FAILURES ==================================='
E           and: '________________________________ test_settings _________________________________'
E           and: ''
E           and: '    def test_settings():'
E           and: ">       assert 'django' not in sys.modules"
E           and: "E       AssertionError: assert 'django' not in {'PIL': <module 'PIL' from '/usr/lib64/python3.6/site-packages/PIL/__init__.py'>, 'PIL.BlpImagePlugin': <module 'PIL.B...ePlugin': <module 'PIL.BufrStubImagePlugin' from '/usr/lib64/python3.6/site-packages/PIL/BufrStubImagePlugin.py'>, ...}"
E           and: "E        +  where {'PIL': <module 'PIL' from '/usr/lib64/python3.6/site-packages/PIL/__init__.py'>, 'PIL.BlpImagePlugin': <module 'PIL.B...ePlugin': <module 'PIL.BufrStubImagePlugin' from '/usr/lib64/python3.6/site-packages/PIL/BufrStubImagePlugin.py'>, ...} = sys.modules"
E           and: ''
E           and: 'test_django_not_loaded_without_settings.py:3: AssertionError'
E           and: '=========================== 1 failed in 0.08 seconds ==========================='
E       remains unmatched: '*1 passed*'

/BUILD/pytest-django-3.4.5/tests/test_django_settings_module.py:278: Failed
--------------------------------------- Captured stdout call ---------------------------------------
running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0/runpytest-0
     in: /tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0/.hypothesis/examples')
rootdir: /tmp/pytest-of-stig/pytest-26/test_django_not_loaded_without_settings0, inifile:
plugins: django-3.4.5, forked-0.2, cov-2.6.0, hypothesis-3.85.1
collected 1 item

test_django_not_loaded_without_settings.py F                             [100%]

=================================== FAILURES ===================================
________________________________ test_settings _________________________________

    def test_settings():
>       assert 'django' not in sys.modules
E       AssertionError: assert 'django' not in {'PIL': <module 'PIL' from '/usr/lib64/python3.6/site-packages/PIL/__init__.py'>, 'PIL.BlpImagePlugin': <module 'PIL.B...ePlugin': <module 'PIL.BufrStubImagePlugin' from '/usr/lib64/python3.6/site-packages/PIL/BufrStubImagePlugin.py'>, ...}
E        +  where {'PIL': <module 'PIL' from '/usr/lib64/python3.6/site-packages/PIL/__init__.py'>, 'PIL.BlpImagePlugin': <module 'PIL.B...ePlugin': <module 'PIL.BufrStubImagePlugin' from '/usr/lib64/python3.6/site-packages/PIL/BufrStubImagePlugin.py'>, ...} = sys.modules

test_django_not_loaded_without_settings.py:3: AssertionError
=========================== 1 failed in 0.08 seconds ===========================
===================================== short test summary info ======================================
SKIP [1] /BUILD/pytest-django-3.4.5/tests/test_django_configurations.py:8: could not import 'configurations'
SKIP [1] /BUILD/pytest-django-3.4.5/tests/test_database.py:94: transactions and reset_sequences must be supported by the database to run this test
SKIP [2] /BUILD/pytest-django-3.4.5/pytest_django_test/db_helpers.py:59: Do not test db reuse since database does not support it
SKIP [1] tests/test_db_setup.py:216: Django 1.9 requires migration and has no concept of initial data fixtures
========================= 2 failed, 156 passed, 5 skipped in 86.37 seconds =========================
```

**Comment by kekePower** [comment] 2019-01-10 23:34
And

```
% python3 setup.py test
running test
running egg_info
writing pytest_django.egg-info/PKG-INFO
writing dependency_links to pytest_django.egg-info/dependency_links.txt
writing entry points to pytest_django.egg-info/entry_points.txt
writing requirements to pytest_django.egg-info/requires.txt
writing top-level names to pytest_django.egg-info/top_level.txt
reading manifest file 'pytest_django.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory '.git'
warning: no previously-included files matching '*' found under directory '.tox'
warning: no previously-included files matching '*' found under directory 'bin'
warning: no previously-included files matching '*' found under directory 'include'
warning: no previously-included files matching '*' found under directory 'lib'
warning: no previously-included files matching '*' found under directory 'share'
warning: no previously-included files matching '*' found under directory 'src'
writing manifest file 'pytest_django.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    entry_points={'pytest11': ['django = pytest_django.plugin']})
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/BUILD/pytest-django-3.4.5/pytest_django_test/db_helpers.py", line 15, in <module>
    TEST_DB_NAME = _settings['TEST']['NAME']
KeyError: 'TEST'
```

**Comment by blueyed** [comment] 2019-02-03 23:42
1. One problem is that it expects pytest-xdist to be installed, this should be skipped without it probably:

> pytest.py: error: unrecognized arguments: -n1

2. Re `test_django_not_loaded_without_settings`:

> assert 'django' not in sys.modules

Maybe something else imports django there?

3. `python3 setup.py test` is not supported I guess.

**Comment by blueyed** [comment] 2019-02-06 11:58
With master 1. should be fixed, but 2. likely needs more investigation from your side (but haven't actually tried to reproduce/trigger it).  Can you please re-try, and provide more steps on how to trigger 2.?

**Comment by blueyed** [comment] 2019-02-06 11:59
Re 2. it might be helpful to print `inspect.getfile(sys.modules['django'])` before the assertion for example.

**Comment by blueyed** [comment] 2019-02-11 16:20
btw: pytest-runner could be used for `python setup.py test`, but since it is required for installation then already not likely worth it.  Ref: https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner.

**Closed** 2019-02-26 15:18 UTC
