### ISSUE TITLE
Queries with related managers don't raise an exception when the test is not marked with django_db

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-django#250] opened 2015-07-27 15:35 UTC
Here's a simple test case to reproduce the problem:
```python
class Bar(models.model):
  pass
class Foo(models.Model):
  bar = models.ManyToMany(Bar)
def test():
  foo = Foo()
  foo.pk = 1
  foo.bar.all()
```

I expected to get an exception like any other database operation.

**Comment by Stranger6667** [comment] 2015-08-14 15:21
Probably it is because querysets are lazy. If you will try to evaluate it, then you will get error.

**Comment by thedrow** [comment] 2015-08-16 08:45
Nope, I evaluated it and it still doesn't fail. It seems that we're not monkeypatching them.

**Comment by Stranger6667** [comment] 2015-08-16 08:57
So, can you provide your test case? This test works well (based on pytest-django test suite):

```python

def test_noaccess():
    with pytest.raises(pytest.fail.Exception):
        Item.objects.create(name='spam')
    with pytest.raises(pytest.fail.Exception):
        Item.objects.count()
    related = Related()
    related.pk = 1
    queryset = related.items.all()
    with pytest.raises(pytest.fail.Exception):
        list(queryset)
```

**Comment by pelme** [comment] 2015-08-16 14:29
Thanks for the report! I also created a small project and came to the same conclusion as @Stranger6667. `all()` is lazy and does not trigger a query by itself, but when forcing the value with `list(...)` the proper exception is raised.

I'm closing this issue for now, please provide more details on how to reproduce this and reopen this issue if something needs fixing!

**Closed by pelme** 2015-08-16 14:29 UTC
