### ISSUE TITLE
Django debug should be optional

### ISSUE THREAD

**Issue by tpmullan** [pytest-dev/pytest-django#846] opened 2020-05-26 16:58 UTC
https://github.com/pytest-dev/pytest-django/blob/162263f338d863fddc14b0659f506d63799f78e1/pytest_django/plugin.py#L473

Currently django is hard codded to not allow debug.  This means that static files are not served, even when debug is set as true.  So in my tests when loading from staticfiles_storage the files are not found without a collect static.  What is the expected way to deal with this?

**Comment by S-Mann** [comment] 2020-05-26 20:54
I get having a default flag for DEBUG = False. But if in user's settings they explicitly specify DEBUG = True. I don't think the library should override it.

**Comment by countermeasure** [comment] 2020-08-06 03:30
I prefer to run tests with ``DEBUG`` set to ``True``, and I can't seem to do that with pytest-django.

Am I missing something, or if I'm not, is there a workaround?

The benefit of doing this is that when a test fails because of an unhandled exception, the resulting screenshot contains debugging information.

**Comment by bluetech** [comment] 2020-10-16 20:59
Duplicate of #180.

This is done to match Django's behavior: https://docs.djangoproject.com/en/dev/topics/testing/overview/#other-test-conditions

But seems like Django has since added a [`--debug-mode` flag](https://docs.djangoproject.com/en/3.1/ref/django-admin/#test) to enable DEBUG. So we can probably do the same. I'll look into it now.

**Comment by bluetech** [comment] 2020-10-16 21:52
PR in #888 if you want to test it!

**Closed** 2020-10-17 12:16 UTC
