### ISSUE TITLE
pytest.mark.django_db does not (always) seem to work in pytest 2.8.x?

### ISSUE THREAD

**Issue by dirkmoors** [pytest-dev/pytest-django#288] opened 2015-10-20 08:16 UTC
Given the following code:
```python
from six import with_metaclass
from abc import ABCMeta, abstractmethod

import pytest

#  more imports ...

class AbstractUserAPITests(with_metaclass(ABCMeta, object)):
    @abstractmethod
    def test_list_users(self):
        pass

@pytest.mark.django_db
class NotAuthenticatedAPITests(AbstractUserAPITests, APITestCase):
    def test_list_users(self):
        # Create some users
        [UserFactory() for _ in range(3)]

        # Assert that unauthorized users cannot find users by listing
        response = self.client.get(reverse('api:user-list'))
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

@pytest.mark.django_db
class RegularUserAPITests(AbstractUserAPITests, APITestCase):
    def test_list_users(self):
        # Create some users
        [UserFactory() for _ in range(3)]

        # Create user with password
        user, password = create_user_with_password()

        # Login
        result = self.client.login(email=user.email, password=password)
        self.assertTrue(result)

        # Assert that authenticated users cannot find users by listing
        response = self.client.get(reverse('api:user-list'))
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(UUID(response.data[0]['guid']), user.guid)
```
When I run pytest 2.8.x,  I get the following error for all the tests in NotAuthenticatedAPITests:
```
F
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/test/testcases.py:182: in __call__
    self._pre_setup()
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/test/testcases.py:787: in _pre_setup
    self._fixture_setup()
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/test/testcases.py:993: in _fixture_setup
    self.atomics = self._enter_atomics()
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/test/testcases.py:933: in _enter_atomics
    atomics[db_name].__enter__()
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/db/transaction.py:183: in __enter__
    connection._start_transaction_under_autocommit()
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py:299: in _start_transaction_under_autocommit
    self.cursor().execute("BEGIN")
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/db/backends/base/base.py:164: in cursor
    cursor = self.make_cursor(self._cursor())
Work/env/vikingco-vikingid-provider/lib/python3.4/site-packages/django/db/backends/base/base.py:450: in make_cursor
    return utils.CursorWrapper(cursor, self)
E   Failed: Database access not allowed, use the "django_db" mark to enable it.
```
I do NOT get the same error for tests in RegularUserAPITests

**Comment by pelme** [comment] 2015-12-05 17:58
Hmm, you should not need django_db at all since you are subclassing from Django's TestCase, django_db should be implied.

Does it fail in the same way if you remove `AbstractUserAPITests`? Can you reproduce the error with a smaller example that you can share? Then we could probably make a test case out of it and fix it.

**Comment by zdenekmaxa** [comment] 2015-12-07 10:08
Perhaps related, I have encountered unexpected behaviour with plain pytest stale, setup_method and the django_db marker: I have summarized the problem here:
http://stackoverflow.com/questions/34089425/django-pytest-setup-method-database-issue

**Comment by pelme** [comment] 2015-12-07 10:17
@zdenekmaxa The error message is the same regardless of where it is triggered from, and it looks like it is different issues. I've responded to the Stackoverflow post and opened a new issue with regard to the setup_X error message.

**Comment by pelme** [comment] 2016-06-21 15:37
I'm closing this issue for now, if you or anyone else is still having this issue with the latest version, please provide a smaller test case where we can reliably reproduce this issue. Thanks!

**Closed by pelme** 2016-06-21 15:37 UTC
