### ISSUE TITLE
Cannot access db in fixtures at 'session' level.

### ISSUE THREAD

**Issue by ludbek** [pytest-dev/pytest-django#388] opened 2016-09-05 09:06 UTC
I am trying to auto use a fixture at `session` level. So I kept the fixture at `conftest.py`. The code is as follows.

``` python
import pytest

pytestmark = [
    pytest.mark.django_db(transaction = True),]

@pytest.fixture(scope="session", autouse = True)
def afixture():
    a_func_which_talks_to_db()
```

Running test throws following error.
`Failed: Database access not allowed, use the "django_db" mark to enable it.`

**Comment by ludbek** [comment] 2017-02-27 11:52
ping

**Comment by goetzk** [comment] 2018-03-09 09:19
I have no help to offer particularly, other than to note while researching a different problem I've seen issues (like #33) which mention the scope must be function. I'm not sure if that is still the case but YVMV.

**Comment by blueyed** [comment] 2019-04-11 21:04
Closing as duplicate of https://github.com/pytest-dev/pytest-django/issues/514.

**Closed by blueyed** 2019-04-11 21:04 UTC
