### ISSUE TITLE
Difference between pytest --reuse-db and manage.py --keepdb

### ISSUE THREAD

**Issue by danizen** [pytest-dev/pytest-django#704] opened 2019-02-25 17:30 UTC
**The Problem**

So, Django's own test runner, and the django-nose test runner, both include an argument `--keepdb`.  However, this works differently than the `--reuse-db` argument to pytest.   Tangentially, the `REUSE_DB=1` environment variable for django-nose works more like pytest's `--reuse-db`.   pytest's behavior would make sense if `--reuse-db` were just for performance, rather than also being used in enterprise environments where CREATE DATABASE is not allowed.

**Desired Behavior**

The authors thought carefully about the naming of `reuse-db`, so I hesitate to argue that it should stub `_create_test_db` rather than `create_test_db`.   However, either `reuse-db` should stub `_create_test_db` or there should optionally be a new argument `keepdb` that matches the behavior of Django's test runner.

**Workaround**

I think I could achieve the same logic in a plugin, or in some fixture which takes the django_db fixture as a decorator, and then runs the migrations.  Please advise on a suggestion for this.

**Comment by blueyed** [comment] 2019-02-26 13:53
Hmm, the problem is not really clear to me.
`--reuse-db` was added mainly for performance reasons I guess.

It gets mapped to Django's keepdb after all: https://github.com/blueyed/pytest-django/blob/17d639c409cd42fb8facd817fe0404178d45514f/pytest_django/fixtures.py#L101-L102

off-topic - recognized this is dead code:
It monkeypatches `create_test_db`, likely just because `_create_test_db` was not available there by then - the feature is much older than Django's `--keepdb`.  But this is likely not true - at least it was there already when keepdb was added in https://github.com/django/django/commit/b7aa7c4ab4372d2b7994d252c8bc87f77dd217ae (since Django 1.0 / https://github.com/django/django/commit/9dc4ba875f21d5690f6ad5995123a67a3c44bafe).

**Comment by danizen** [comment] 2019-02-27 01:30
@blueyed , it looks like `monkey_patch_for_db_reuse` may be the dead code.  I'll actually test how whether creation.create_test_db (in the backend) is called at all.   It may be that the one where I set a breakpoint was with django-nose.

**Comment by blueyed** [comment] 2019-02-27 06:57
Ok, then it was mostly a misunderstanding I guess.
The dead code is removed by now.

I think we should revisit the doc (https://github.com/pytest-dev/pytest-django/blame/743ea268398141ddab22b2bbd36f3f4131838658/docs/database.rst#L89-L126) and help text, and mention there that this is the same as Django's `--keepdb`, as far as I can see.

**Comment by blueyed** [comment] 2019-03-13 23:01
Closing for now.

**Closed by blueyed** 2019-03-13 23:01 UTC
