### ISSUE TITLE
Data migrations failing

### ISSUE THREAD

**Issue by knyghty** [pytest-dev/pytest-django#572] opened 2018-01-31 00:41 UTC
Probably related to #341.

Data migrations are failing, and I don't know of any way to get a traceback for this. It runs fine using regular `./manage.py test` but pytest doesn't seem to like them. As soon as a data migration runs, it errors. Then the test suite immediately starts and of course most tests error out as the database isn't in the right state.

Is it something about accessing the database during migrations that doesn't work here? When I comment out the body of the migration, it works fine.

Also, I'm using standard django TestCase classes, and database access doesn't work until I added this from the docs:

```
@pytest.fixture(autouse=True)
def enable_db_access_for_all_tests(db):
    pass
```

I'm not sure if this is the expected behaviour.

**Comment by bluetech** [comment] 2020-10-16 18:54
In my project I have data migrations and they are running fine. We need some way to reproduce this, otherwise not much we can do. Since a lot of time has passed I'll close this, but will reopen if more details are provided.

**Closed by bluetech** 2020-10-16 18:54 UTC
